
[domains]
frontend_domain = "https://hotel-front-g2oixt69b-alexansaas-projects.vercel.app"
[views]
admin_view = "https://hotel-front-g2oixt69b-alexansaas-projects.vercel.app/adminHome"
user_view = "https://hotel-front-g2oixt69b-alexansaas-projects.vercel.app/"
